<?php
namespace Modules\Activity\Controllers;

use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Activity\Models\Activity;
use Modules\Activity\Models\ActivityCategory;
use Modules\Activity\Models\ActivityTranslation;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Activity\Models\ActivityTerm;
use Modules\Booking\Models\Booking;

class ManageActivityController extends FrontendController
{
    protected $activityClass;
    protected $activityTranslationClass;
    protected $activityCategoryClass;
    protected $activityTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;

    public function __construct()
    {
        $this->activityClass = Activity::class;
        $this->activityTranslationClass = ActivityTranslation::class;
        $this->activityCategoryClass = ActivityCategory::class;
        $this->activityTermClass = ActivityTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;
        parent::__construct();
    }

    public function callAction($method, $parameters)
    {
        if (setting_item('activity_disable')) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function manageActivity(Request $request)
    {
        $this->checkPermission('activity_view');
        $user_id = Auth::id();
        $list_activity = $this->activityClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_activity->paginate(5),
            'breadcrumbs' => [
                [
                    'name' => __('Manage Activities'),
                    'url'  => route('activity.vendor.index'),
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Manage Activities"),
        ];
        return view('Activity::frontend.manageActivity.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('activity_view');
        $user_id = Auth::id();
        $list_activity = $this->activityClass::onlyTrashed()->where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows'        => $list_activity->paginate(5),
            'recovery'           => 1,
            'breadcrumbs' => [
                [
                    'name' => __('Manage Activities'),
                    'url'  => route('activity.vendor.index'),
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Recovery Activities"),
        ];
        return view('Activity::frontend.manageActivity.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('activity_delete');
        $user_id = Auth::id();
        $query = $this->activityClass::onlyTrashed()->where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
        }
        return redirect(route('activity.vendor.recovery'))->with('success', __('Restore activity success!'));
    }

    public function createActivity(Request $request)
    {
        $this->checkPermission('activity_create');
        $row = new $this->activityClass();
        $data = [
            'row'           => $row,
            'translation'   => new $this->activityTranslationClass(),
            'activity_category' => $this->activityCategoryClass::get()->toTree(),
            'activity_location' => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'activity')->get(),
            'breadcrumbs'   => [
                [
                    'name' => __('Manage Activities'),
                    'url'  => route('activity.vendor.index'),
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'    => __("Create Activities"),
        ];
        return view('Activity::frontend.manageActivity.detail', $data);
    }

    public function editActivity(Request $request, $id)
    {
        $this->checkPermission('activity_update');
        $user_id = Auth::id();
        $row = $this->activityClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('activity.vendor.index'))->with('warning', __('Activity not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'            => $row,
            'activity_category'  => $this->activityCategoryClass::where("status", "publish")->get()->toTree(),
            'activity_location'  => $this->locationClass::where("status", "publish")->get()->toTree(),
            'attributes'     => $this->attributesClass::where('service', 'activity')->get(),
            "selected_terms" => $row->activity_term->pluck('term_id'),
            'breadcrumbs'    => [
                [
                    'name' => __('Manage Activities'),
                    'url'  => route('activity.vendor.index'),
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'     => __("Edit Activities"),
        ];
        return view('Activity::frontend.manageActivity.detail', $data);
    }

    public function store(Request $request, $id)
    {
        if ($id > 0) {
            $this->checkPermission('activity_update');
            $row = $this->activityClass::find($id);
            if (empty($row)) {
                return redirect(route('activity.vendor.edit', ['id' => $row->id]));
            }
            if ($row->create_user != Auth::id() and !$this->hasPermission('activity_manage_others')) {
                return redirect(route('activity.vendor.edit', ['id' => $row->id]));
            }
        } else {
            $this->checkPermission('activity_create');
            $row = new $this->activityClass();
            $row->status = "publish";
            if (setting_item("activity_vendor_create_service_must_approved_by_admin", 0)) {
                $row->status = "pending";
            }
        }
        $row->fillByAttr([
            'title',
            'content',
            'image_id',
            'banner_image_id',
            'short_desc',
            'category_id',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'gallery',
            'video',
            'default_state',
            'price',
            'sale_price',
            'duration',
            'max_people',
            'min_people',
            'faqs',
            'include',
            'exclude',
            'itinerary',
        ], $request->input());
        $row->ical_import_url = $request->ical_import_url;
        $res = $row->saveOriginOrTranslation($request->input('lang'), true);
        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
                $row->saveMeta($request);
            }
            if ($id > 0) {
                return back()->with('success', __('Activity updated'));
            } else {
                return redirect(route('activity.vendor.edit', ['id' => $row->id]))->with('success', __('Activity created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->activityTermClass::where('activity_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->activityTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'activity_id' => $row->id
                ]);
            }
            $this->activityTermClass::where('activity_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function deleteActivity($id)
    {
        $this->checkPermission('activity_delete');
        $user_id = Auth::id();
        $query = $this->activityClass::where("create_user", $user_id)->where("id", $id)->first();
        if (!empty($query)) {
            $query->delete();
        }
        return redirect(route('activity.vendor.index'))->with('success', __('Delete activity success!'));
    }

    public function bulkEditActivity($id, Request $request)
    {
        $this->checkPermission('activity_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->activityClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if (empty($query)) {
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action) {
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReport(Request $request)
    {
        $data = [
            'bookings'    => $this->bookingClass::getBookingHistory($request->input('status'), false, Auth::id(), 'activity'),
            'statues'     => config('booking.statuses'),
            'breadcrumbs' => [
                [
                    'name' => __('Manage Activities'),
                    'url'  => route('activity.vendor.index'),
                ],
                [
                    'name'  => __('Booking Report'),
                    'class' => 'active'
                ],
            ],
            'page_title'  => __("Booking Report"),
        ];
        return view('Activity::frontend.manageActivity.bookingReport', $data);
    }

    public function bookingReportBulkEdit($booking_id, Request $request)
    {
        $status = $request->input('status');
        if (!empty(setting_item("activity_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if (!empty($item)) {
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                $item->sendStatusUpdatedEmails();
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }

    public function cloneActivity(Request $request, $id)
    {
        $this->checkPermission('activity_update');
        $user_id = Auth::id();
        $row = $this->activityClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('activity.vendor.index'))->with('warning', __('Activity not found!'));
        };
        try {
            $clone = $row->replicate();
            $clone->status = 'draft';
            $clone->push();
            if (!empty($row->activity_term)) {
                foreach ($row->activity_term as $term) {
                    $e = $term->replicate();
                    if ($e->push()) {
                        $clone->activity_term()->save($e);
                    }
                }
            }
            if (!empty($row->meta)) {
                $e = $row->meta->replicate();
                if ($e->push()) {
                    $clone->meta()->save($e);
                }
            }
            if (!empty($row->translations)) {
                foreach ($row->translations as $translation) {
                    $e = $translation->replicate();
                    $e->origin_id = $clone->id;
                    if ($e->push()) {
                        $clone->translations()->save($e);
                    }
                }
            }
            return redirect()->back()->with('success', __('Activity clone was successful'));
        } catch (\Exception $exception) {
            $clone->delete();
            return redirect()->back()->with('warning', __($exception->getMessage()));
        }
    }
}
