<?php
namespace Modules\Sauna\Controllers;

use Modules\Sauna\Models\Sauna;
use Modules\Sauna\Models\SaunaTerm;
use Modules\Sauna\Models\SaunaTranslation;
use Modules\FrontendController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Location\Models\Location;
use Modules\Core\Models\Attributes;
use Modules\Booking\Models\Booking;

class VendorSaunaController extends FrontendController
{
    protected $saunaClass;
    protected $saunaTranslationClass;
    protected $saunaTermClass;
    protected $attributesClass;
    protected $locationClass;
    protected $bookingClass;
    public function __construct()
    {
        parent::__construct();
        $this->saunaClass = Sauna::class;
        $this->saunaTranslationClass = SaunaTranslation::class;
        $this->saunaTermClass = SaunaTerm::class;
        $this->attributesClass = Attributes::class;
        $this->locationClass = Location::class;
        $this->bookingClass = Booking::class;
    }

    public function callAction($method, $parameters)
    {
        if(!Sauna::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function indexSauna(Request $request)
    {
        $this->checkPermission('sauna_view');
        $user_id = Auth::id();
        $list_tour = $this->saunaClass::where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Saunas'),
                    'url'  => route('sauna.vendor.index')
                ],
                [
                    'name'  => __('All'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Manage Saunas"),
        ];
        return view('Sauna::frontend.vendorSauna.index', $data);
    }

    public function recovery(Request $request)
    {
        $this->checkPermission('sauna_view');
        $user_id = Auth::id();
        $list_tour = $this->saunaClass::onlyTrashed()->where("create_user", $user_id)->orderBy('id', 'desc');
        $data = [
            'rows' => $list_tour->paginate(5),
            'recovery'           => 1,
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Saunas'),
                    'url'  => route('sauna.vendor.index')
                ],
                [
                    'name'  => __('Recovery'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Recovery Saunas"),
        ];
        return view('Sauna::frontend.vendorSauna.index', $data);
    }

    public function restore($id)
    {
        $this->checkPermission('sauna_delete');
        $user_id = Auth::id();
        $query = $this->saunaClass::onlyTrashed()->where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->restore();
        }
        return redirect(route('sauna.vendor.recovery'))->with('success', __('Restore sauna success!'));
    }

    public function createSauna(Request $request)
    {
        $this->checkPermission('sauna_create');
        $row = new $this->saunaClass();
        $data = [
            'row'           => $row,
            'translation' => new $this->saunaTranslationClass(),
            'sauna_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'sauna')->get(),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Saunas'),
                    'url'  => route('sauna.vendor.index')
                ],
                [
                    'name'  => __('Create'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Create Saunas"),
        ];
        return view('Sauna::frontend.vendorSauna.detail', $data);
    }


    public function store( Request $request, $id ){
        if($id>0){
            $this->checkPermission('sauna_update');
            $row = $this->saunaClass::find($id);
            if (empty($row)) {
                return redirect(route('sauna.vendor.index'));
            }

            if($row->create_user != Auth::id() and !$this->hasPermission('sauna_manage_others'))
            {
                return redirect(route('sauna.vendor.index'));
            }
        }else{
            $this->checkPermission('sauna_create');
            $row = new $this->saunaClass();
            $row->status = "publish";
            if(setting_item("sauna_vendor_create_service_must_approved_by_admin", 0)){
                $row->status = "pending";
            }
        }
        $dataKeys = [
            'title',
            'content',
            'price',
            'is_instant',
            'video',
            'faqs',
            'image_id',
            'banner_image_id',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'duration',
            'start_time',
            'price',
            'sale_price',
            'ticket_types',
            'enable_extra_price',
            'extra_price',
            'is_featured',
            'default_state',
        ];
        if($this->hasPermission('sauna_manage_others')){
            $dataKeys[] = 'create_user';
        }

        $row->fillByAttr($dataKeys,$request->input());

        $res = $row->saveOriginOrTranslation($request->input('lang'),true);

        if ($res) {
            if(!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if($id > 0 ){
                return back()->with('success',  __('Sauna updated') );
            }else{
                return redirect(route('sauna.vendor.edit',['id'=>$row->id]))->with('success', __('Sauna created') );
            }
        }
    }

    public function saveTerms($row, $request)
    {
        if (empty($request->input('terms'))) {
            $this->saunaTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->saunaTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->saunaTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function editSauna(Request $request, $id)
    {
        $this->checkPermission('sauna_update');
        $user_id = Auth::id();
        $row = $this->saunaClass::where("create_user", $user_id);
        $row = $row->find($id);
        if (empty($row)) {
            return redirect(route('sauna.vendor.index'))->with('warning', __('Sauna not found!'));
        }
        $translation = $row->translateOrOrigin($request->query('lang'));
        $data = [
            'translation'    => $translation,
            'row'           => $row,
            'sauna_location' => $this->locationClass::where("status","publish")->get()->toTree(),
            'attributes'    => $this->attributesClass::where('service', 'sauna')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Saunas'),
                    'url'  => route('sauna.vendor.index')
                ],
                [
                    'name'  => __('Edit'),
                    'class' => 'active'
                ],
            ],
            'page_title'         => __("Edit Saunas"),
        ];
        return view('Sauna::frontend.vendorSauna.detail', $data);
    }

    public function deleteSauna($id)
    {
        $this->checkPermission('sauna_delete');
        $user_id = Auth::id();
        $query = $this->saunaClass::where("create_user", $user_id)->where("id", $id)->first();
        if(!empty($query)){
            $query->delete();
        }
        return redirect(route('sauna.vendor.index'))->with('success', __('Delete sauna success!'));
    }

    public function bulkEditSauna($id , Request $request){
        $this->checkPermission('sauna_update');
        $action = $request->input('action');
        $user_id = Auth::id();
        $query = $this->saunaClass::where("create_user", $user_id)->where("id", $id)->first();
        if (empty($id)) {
            return redirect()->back()->with('error', __('No item!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        if(empty($query)){
            return redirect()->back()->with('error', __('Not Found'));
        }
        switch ($action){
            case "make-hide":
                $query->status = "draft";
                break;
            case "make-publish":
                $query->status = "publish";
                break;
        }
        $query->save();
        return redirect()->back()->with('success', __('Update success!'));
    }

    public function bookingReport(Request $request)
    {
        $data = [
            'bookings' => $this->bookingClass::getBookingHistory($request->input('status'), false , Auth::id() , 'sauna'),
            'statues'  => config('booking.statuses'),
            'breadcrumbs'        => [
                [
                    'name' => __('Manage Sauna'),
                    'url'  => route('sauna.vendor.index')
                ],
                [
                    'name' => __('Booking Report'),
                    'class'  => 'active'
                ]
            ],
            'page_title'         => __("Booking Report"),
        ];
        return view('Sauna::frontend.vendorSauna.bookingReport', $data);
    }

    public function bookingReportBulkEdit($booking_id , Request $request){
        $status = $request->input('status');
        if (!empty(setting_item("sauna_allow_vendor_can_change_their_booking_status")) and !empty($status) and !empty($booking_id)) {
            $query = $this->bookingClass::where("id", $booking_id);
            $query->where("vendor_id", Auth::id());
            $item = $query->first();
            if(!empty($item)){
                $item->status = $status;
                $item->save();

                if($status == Booking::CANCELLED) $item->tryRefundToWallet();

                $item->sendStatusUpdatedEmails();
                return redirect()->back()->with('success', __('Update success'));
            }
            return redirect()->back()->with('error', __('Booking not found!'));
        }
        return redirect()->back()->with('error', __('Update fail!'));
    }
}
